title: Jude Research Portfolio
description: >-
  AI-driven biomedical engineering researcher working across medical imaging,
  signal processing, and human-centered intelligent systems.
baseurl: "/resume"
url: "https://pinkr1ver.github.io"

timezone: "UTC"
markdown: kramdown
theme: minima

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:slug/
  education:
    output: true
    permalink: /education/:slug/
  about:
    output: true
    permalink: /about/:slug/
  publications:
    output: true
    permalink: /publications/:slug/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
  - scope:
      path: ""
      type: "education"
    values:
      layout: education

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - resume-pdf
  - node_modules
  - vendor

permalink: pretty
show_socials: true
